/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as Free15MinCallWithKatieRouteImport } from './routes/free-15-min-call-with-katie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const Free15MinCallWithKatieRoute = Free15MinCallWithKatieRouteImport.update({
  id: '/free-15-min-call-with-katie',
  path: '/free-15-min-call-with-katie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/conditions': typeof ConditionsRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/scheduler': typeof SchedulerRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/conditions': typeof ConditionsRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/scheduler': typeof SchedulerRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/conditions': typeof ConditionsRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/scheduler': typeof SchedulerRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/conditions'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/scheduler'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/conditions'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/scheduler'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/conditions'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/scheduler'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ConditionsRoute: typeof ConditionsRoute
  ContactRoute: typeof ContactRoute
  Free15MinCallWithKatieRoute: typeof Free15MinCallWithKatieRoute
  SchedulerRoute: typeof SchedulerRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-15-min-call-with-katie': {
      id: '/free-15-min-call-with-katie'
      path: '/free-15-min-call-with-katie'
      fullPath: '/free-15-min-call-with-katie'
      preLoaderRoute: typeof Free15MinCallWithKatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ConditionsRoute: ConditionsRoute,
  ContactRoute: ContactRoute,
  Free15MinCallWithKatieRoute: Free15MinCallWithKatieRoute,
  SchedulerRoute: SchedulerRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
