/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeTreatRouteImport } from './routes/what-we-treat'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MichiganDiscoveryCallRouteImport } from './routes/michigan-discovery-call'
import { Route as Free15MinCallWithKatieRouteImport } from './routes/free-15-min-call-with-katie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaritySessionRouteImport } from './routes/clarity-session'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRouteImport } from './routes/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'

const WhatWeTreatRoute = WhatWeTreatRouteImport.update({
  id: '/what-we-treat',
  path: '/what-we-treat',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MichiganDiscoveryCallRoute = MichiganDiscoveryCallRouteImport.update({
  id: '/michigan-discovery-call',
  path: '/michigan-discovery-call',
  getParentRoute: () => rootRouteImport,
} as any)
const Free15MinCallWithKatieRoute = Free15MinCallWithKatieRouteImport.update({
  id: '/free-15-min-call-with-katie',
  path: '/free-15-min-call-with-katie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaritySessionRoute = ClaritySessionRouteImport.update({
  id: '/clarity-session',
  path: '/clarity-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute =
  BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRouteImport.update({
    id: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted',
    path: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/clarity-session': typeof ClaritySessionRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/michigan-discovery-call': typeof MichiganDiscoveryCallRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-treat': typeof WhatWeTreatRoute
  '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/clarity-session': typeof ClaritySessionRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/michigan-discovery-call': typeof MichiganDiscoveryCallRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-treat': typeof WhatWeTreatRoute
  '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/clarity-session': typeof ClaritySessionRoute
  '/contact': typeof ContactRoute
  '/free-15-min-call-with-katie': typeof Free15MinCallWithKatieRoute
  '/michigan-discovery-call': typeof MichiganDiscoveryCallRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-treat': typeof WhatWeTreatRoute
  '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/approach'
    | '/clarity-session'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/michigan-discovery-call'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/what-we-treat'
    | '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/approach'
    | '/clarity-session'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/michigan-discovery-call'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/what-we-treat'
    | '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/approach'
    | '/clarity-session'
    | '/contact'
    | '/free-15-min-call-with-katie'
    | '/michigan-discovery-call'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/what-we-treat'
    | '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  ClaritySessionRoute: typeof ClaritySessionRoute
  ContactRoute: typeof ContactRoute
  Free15MinCallWithKatieRoute: typeof Free15MinCallWithKatieRoute
  MichiganDiscoveryCallRoute: typeof MichiganDiscoveryCallRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhatWeTreatRoute: typeof WhatWeTreatRoute
  BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute: typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-treat': {
      id: '/what-we-treat'
      path: '/what-we-treat'
      fullPath: '/what-we-treat'
      preLoaderRoute: typeof WhatWeTreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/michigan-discovery-call': {
      id: '/michigan-discovery-call'
      path: '/michigan-discovery-call'
      fullPath: '/michigan-discovery-call'
      preLoaderRoute: typeof MichiganDiscoveryCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-15-min-call-with-katie': {
      id: '/free-15-min-call-with-katie'
      path: '/free-15-min-call-with-katie'
      fullPath: '/free-15-min-call-with-katie'
      preLoaderRoute: typeof Free15MinCallWithKatieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarity-session': {
      id: '/clarity-session'
      path: '/clarity-session'
      fullPath: '/clarity-session'
      preLoaderRoute: typeof ClaritySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted': {
      id: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
      path: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
      fullPath: '/blog/why-michigan-women-over-40-cant-lose-weight-feel-exhausted'
      preLoaderRoute: typeof BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  ClaritySessionRoute: ClaritySessionRoute,
  ContactRoute: ContactRoute,
  Free15MinCallWithKatieRoute: Free15MinCallWithKatieRoute,
  MichiganDiscoveryCallRoute: MichiganDiscoveryCallRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhatWeTreatRoute: WhatWeTreatRoute,
  BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute:
    BlogWhyMichiganWomenOver40CantLoseWeightFeelExhaustedRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
